# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceOrder', '0002_remove_exam_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='patitent',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='serviceorderexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exams', to='serviceOrder.Exam'),
        ),
    ]
