# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceOrder', '0003_auto_20180818_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceOrder.Exam'),
        ),
        migrations.AlterField(
            model_name='serviceorderexam',
            name='serviceOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='serviceOrder.ServiceOrder'),
        ),
    ]
