# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-18 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceOrder', '0004_auto_20180818_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderexam',
            name='status',
            field=models.CharField(choices=[(b'waiting', b'Waiting'), (b'processing', b'Processing'), (b'canceled', b'Canceled'), (b'available', b'Available'), (b'taken', b'Taken')], default=b'waiting', max_length=50),
        ),
    ]
